AGENT_KEYWORDS = {

    "code": [
        "python",
        "java",
        "javascript",
        "typescript",
        "c++",
        "programming",
        "code",
        "coding",
        "debug",
        "bug",
        "error",
        "api",
        "fastapi",
        "django",
        "flask",
        "react",
        "next.js",
        "database",
        "sql",
        "algorithm",
        "function",
        "class",
        "backend",
        "frontend",
    ],

    "writer": [
        "write",
        "rewrite",
        "essay",
        "story",
        "poem",
        "article",
        "blog",
        "caption",
        "script",
        "creative",
        "content",
        "email",
        "letter",
        "paragraph",
        "summarize",
    ],

    "math": [
        "calculate",
        
        "equation",
        "solve",
        "mathematics",
        "math",
        "algebra",
        "calculus",
        "derivative",
        "integral",
        "probability",
        "statistics",
        "percentage",
        "fraction",
        "geometry",
        "matrix",
        "formula",
    ],

    "research": [
        "research",
        "latest",
        "recent",
        "current",
        "news",
        "history",
        "study",
        "paper",
        "according to",
        "compare",
        "comparison",
        "evidence",
        "facts",
        "information",
        "who is",
        "what happened",
    ],

    "chat": [
        "hello",
        "hi",
        "hey",
        "how are you",
        "what's up",
        "joke",
        "fun",
        "bored",
        "recommend",
        "suggest",
        "opinion",
    ],
}